name: Create Release
on:
  push:
    tags:
      - 'v[0-9]*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'AcsActionBarSaver.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
