name: Create Release
on: push
jobs:
  release-project:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create Folder
      run: mkdir AcsActionBarSaver
    - name: Copy Files to Folder
      run: cp -r !(AcsActionBarSaver) AcsActionBarSaver
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        filename: AcsActionBarSaver.zip
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Create Github Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.${{ github.run_number }}
        release_name: AcsActionBarSaver
    - name: Upload asset to Github Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./AcsActionBarSaver.zip
        asset_name: AcsActionBarSaver.zip
        asset_content_type: application/zip

